# Generated by Django 5.1.1 on 2024-09-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='palavras_chave',
            field=models.TextField(blank=True),
        ),
    ]
