# Generated by Django 5.1.1 on 2024-10-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_manual_palavras_chave'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='manuais/'),
        ),
    ]
